<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * Creates the 'waste_assessments' table to store waste 
     * analytics data generated by the AI assessment.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::create('waste_assessments', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedBigInteger('barangay_id')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('waste_assessments');
    }
};
